
services:
  samplefy:
    build:
      context: .
      dockerfile: Samplefy/Dockerfile
    ports:
      - 5000:80
    depends_on:
      db:
        condition: service_healthy
        
#  functions:
#    build:
#      context: Samplefy.FunctionApp
#    ports:
#      - 5000
      
  samplefy-playlists:
    build:
      context: .
      dockerfile: Samplefy.Playlists/Dockerfile
    ports:
      - 5001:80
    depends_on: 
      - mongodb
      - samplefy
  db:
     image: postgres
     restart: always
     user: postgres
     secrets:
       - db-password
     volumes:
       - db-data:/var/lib/postgresql/data
     environment:
       - POSTGRES_DB=samplefy
       - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
     expose:
       - 5432
     ports:
       - 5432:5432
     healthcheck:
       test: [ "CMD", "pg_isready" ]
       interval: 10s
       timeout: 5s
       retries: 5
       
  mongodb:
    image: mongo
    restart: always
    volumes:
      - db-data:/var/lib/mongo/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: samplefy
      MONGO_INITDB_ROOT_PASSWORD: test
    ports:
      - 27017:27017
volumes:
 db-data:
secrets:
 db-password:
   file: db/password.txt

